### ISSUE TITLE
How to init

### ISSUE THREAD

**Issue by GizmoWeb** [DjeeBay/PasswordManager#31]
hello, I try to test this project. I'm successful started, but I'm not understand how to init it. All db tables are empty and nothing is possible except login, but I'm not able to register any user. Can you help me?

**Comment by GizmoWeb** [comment]
ok, sorry, after some test I was able to add admin user.

**Comment by DjeeBay** [comment]
> ok, sorry, after some test I was able to add admin user.

Well done.
Do not hesitate if you need help or have any suggestions.
